name: explorer
services:
  qrypt-mempool-db:
    image: postgres:16-alpine
    container_name: qrypt-mempool-db
    env_file: [./mempool-db.env]
    volumes: [qrypt_mempool_db:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U \"\$\\" -d \"\$\\""]
      interval: 2s
      timeout: 3s
      retries: 40
    restart: unless-stopped

  qrypt-mempool-api:
    image: explorer-qrypt-mempool-api
    container_name: qrypt-mempool-api
    depends_on:
      qrypt-mempool-db:
        condition: service_healthy
    extra_hosts: ["host.docker.internal:host-gateway"]
    env_file: [./mempool-api.env]
    restart: unless-stopped

  qrypt-mempool-web:
    image: explorer-qrypt-mempool-web
    container_name: qrypt-mempool-web
    depends_on: [qrypt-mempool-api]
    ports: ["8080:8080"]
    volumes:
      - ./ui-patch.js:/usr/share/nginx/html/ui-patch.js:ro
      - ./route-guard.js:/usr/share/nginx/html/route-guard.js:ro
    restart: unless-stopped

volumes:
  qrypt_mempool_db:
    external: true
    name: explorer_qrypt_mempool_db
